# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files # default > 500kB, lfs excluded
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
