name: Item Idea
description: An idea for a new item
title: "[Item Idea]: **Name**"
labels: ["Item Idea"]
body:
  - type: input
    id: description
    attributes:
      label: Description
      description: What should this item do?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Appearance
  - type: input
    attributes:
      label: Item
      description: What Minecraft item should be used?
      placeholder: minecraft:stick
    validations:
      required: true
  - type: input
    attributes:
      label: Lore
      description: What lore should be displayed in the item's tooltip?
      placeholder: Very sticky!

  - type: markdown
    attributes:
      value: |
        ## Obtainment

        How can this item be obtained?

        - In Loot Chests?
        - As Pedestal Item?
        - As Shop Item?
        - On which Levels?
        - As Monster Drop?
        - Crafted?
        - How rare?
        - ...
  - type: textarea
    attributes:
      label: Obtainment

  - type: markdown
    attributes:
      value: |
        ## Interaction
  - type: textarea
    attributes:
      label: Event
      description: When is this item's effect triggered?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Effect
      description: What does the item actually do?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation Notes
      description: How could this be implemented?
