name: Item Idea
description: An idea for a new item
title: "[Item Idea]: Name"
labels: ["Item Idea"]
body:
  - type: input
    attributes:
      label: Description
      description: What should this item do?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Appearance
  - type: input
    attributes:
      label: Item
      description: What Minecraft item should be used?
      placeholder: |
        `minecraft:stick`
    validations:
      required: true
  - type: input
    attributes:
      label: Lore
      description: What lore should be displayed in the item's tooltip?
      placeholder: Very sticky!

  - type: textarea
    attributes:
      label: Obtainment
  - type: markdown
    attributes:
      value: |
        <details>
        <summary>Examples</summary>

        - In Loot Chests
        - As Pedestal Item
        - As Shop Item
        - On which Levels
        - As Monster Drop
        - Crafted
        - Quantity? (useful for consumable items)
        - Rarity?
        - ...
        </details>

  - type: markdown
    attributes:
      value: |
        ## Interaction
  - type: textarea
    attributes:
      label: Event
      description: When is this item's effect triggered?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <details>
        <summary>Examples</summary>

        #### Events

        - Every `<n>` seconds
        - On enter...
          - `<n>` rooms
          - boss room
          - special room
          - next level
        - On clear...
          - `<n>` rooms
          - boss
        - On kill monster
        - On attack monster
        - On take damage
        - On buy item
        - On throw `<item>`
        - On use `<item>`
        - `<instant-event>` after `<n>` seconds
        - `<instant-event>` while `<continous-event>`
        - `<instant-event>` until `<continous-event>`
        - ...

        #### Event Predicates

        - Carrying `<item>` in inventory
        - Holding `<item>` in mainhand/offhand
        - Wearing `<item>`
        - Movement...
          - standing still
          - sneaking
          - walking
          - running
        - Looking...
          - down
          - up
        - Health inside `<range>`
        - ...
        </details>

  - type: textarea
    attributes:
      label: Effect
      description: What exactly does the item do?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <details>
        <summary>Examples</summary>

        #### Effects

        - Give `<n>` `<item>` to `<target>`
        - Clear `<item>` from inventory
        - Give `<target>` `<potion-effect>` `<level>` for `<n>` seconds
        - Set `<target>` on fire for `<n>` seconds
        - Kill `<target>`
        - Spawn `<spawnable>` at `<target>`
        - ...

        #### Effect Targets

        - Current entity
        - `<n>` closest/random entity/player/monster/item in `<range>`
        - ...

        #### Spawnables

        - Monster, Item, etc...
        - Stationary marker
        - Relative marker (`~` or `^`) to another entity
        - Laser that moves `<n>` blocks every `<n>` seconds
        - Orbital with radius `<n>` around `<target>`
        - ...
        </details>

  - type: textarea
    attributes:
      label: Implementation Notes
      description: How could this be implemented?
